// Generated by https://quicktype.io

export interface User {
    ok:   boolean;
    user: UserClass;
}

export interface UserClass {
    nombre: string;
    email:  string;
    online: boolean;
    uid:    string;
}
